version: "3"
services:
  app:
    image: "node:16"
    container_name: app
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./scripts/server.sh:/usr/src/app/scripts/server.sh
      - ./src:/usr/src/app/src
    command: "bash scripts/server.sh"
  json-server:
    image: "node:16"
    container_name: json-server-container
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./scripts/db.sh:/usr/src/app/scripts/db.sh
      - ./src/db:/usr/src/app/db
    command: "bash scripts/db.sh"
